Fix ClusterSecretStore secret token namespace scoping for vault backend
itscontained/secret-manager pull request #80
Opened 2020-10-31 20:09 UTC by yndai

**What this PR does / why we need it**:

This PR updates the vault backend controller logic to respect the namespacing semantics defined in the ClusterSecretStore resource [HERE](https://github.com/itscontained/secret-manager/blob/master/deploy/crds/secret-manager.itscontained.io_clustersecretstores.yaml#L255-L257). Currently, regardless of the resource being a ClusterSecretStore, the controller appears to look for the token secret in the namespace of the referent ExternalSecret.

Example of ClusterSecretStore:
```yaml
apiVersion: secret-manager.itscontained.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: cluster-shared-secrets
spec:
  vault:
    auth:
      kubernetes:
        mountPath: kubernetes
        role: cluster-shared-role
        secretRef:
          name: shared-vault-auth-token-t6cbv
          namespace: infra
    path: apps
    server: <vault-url>
```

Example of error:
```
E1031 19:13:13.389474       1 controller.go:117] controllers/ExternalSecret "msg"="error while reconciling ExternalSecret" "error"="cannot setup store client: unable to setup SecretStore client: error reading Kubernetes service account token. error: Secret \"shared-vault-auth-token-t6cbv\" not found" "externalsecret"={"Namespace":"tony-dai","Name":"shared-secrets"}
```

Verified that it works after this fix:
```
I1031 19:15:05.747593       1 controller.go:131] controllers/ExternalSecret "msg"="successfully reconcile ExternalSecret" "externalsecret"={"Namespace":"tony-dai","Name":"shared-secrets"} "operation"="created"
```

**Other notes for your reviewer**:

**Release note**:

```release-note
- Fixed ClusterSecretStore secret token namespace scoping for vault backend
```

2020-11-02 20:22 UTC, mcavoyk requested changes

2020-11-02 20:22 UTC, mcavoyk commented on pkg/store/vault/vault.go
> +func (v *Vault) secretKeyRef(ctx context.Context, namespace string, secretRef *smmeta.SecretKeySelector) (string, error) {
With this change, should be able to remove `namespace` from function definition, and just use `v.namespace` set from the vault store initialization.

2020-11-03 00:33 UTC, yndai commented
@mcavoyk Thanks for the review, addressed your comments

2020-11-04 04:36 UTC, mcavoyk approved these changes
LGTM

2020-11-04 04:36 UTC, merged